### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by eilc0** [DFIR-HBG/ParseSnapchat#1]
Hi, 
First I'd likle to thank you for you great tool !

I've got an inssue when trying to parse snapchat datas (On windows or Linux) :

```
─# python3 ParseSnapchat.py /home/kali/Desktop/SnapchatFolder /home/kali/Desktop/group.snapchat.picaboo.plist                                                                                      1 ⨯
Running on Linux
Getting User ID from user.plist


Getting friends and groups from group.snapchat.picaboo.plist
Can not find key 'share_user' in plist, getting friends from primary.docobjects
Found key 'user' in plist, this is an older version of storing friends not yet supported by this script

Gathering friends from primary.docobjects
WARNING - WILL contain users that are not friends
Traceback (most recent call last):
  File "/home/kali/ParseSnapchat/ParseSnapchat.py", line 453, in main
    friends_df, group_df = getFriendsPlist(groupPlist)
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1681, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: snapchatter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/ParseSnapchat/ParseSnapchat.py", line 483, in <module>
    main()
  File "/home/kali/ParseSnapchat/ParseSnapchat.py", line 455, in main
    friends_df , group_df= getFriendsPrimary(Path(primaryDoc[0]))
  File "/home/kali/ParseSnapchat/ParseSnapchat.py", line 204, in getFriendsPrimary
    df = pd.read_sql_query(messagesQuery, conn)
  File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 377, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1727, in read_query
    cursor = self.execute(*args)
  File "/usr/lib/python3/dist-packages/pandas/io/sql.py", line 1693, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select
    snapchatter.userId,
    snapchatter.rowid,
    index_snapchatterusername.username
    from snapchatter
    inner join index_snapchatterusername ON snapchatter.rowid=index_snapchatterusername.rowid
    ': no such table: snapchatter
```

Do you have any ideas what's wrong ?

Thank you for your help

**Comment by Ogg3** [comment]
"sqlite3.OperationalError: no such table: snapchatter", I would check if the database actually has data
